"""Episode kernel source — sequential episode leader voice generation.

Extracts short motivic kernels from fugue subject material and chains
them into ascending or descending sequences that fill a target duration
and land on a specified degree. Produces the leader voice for sequential
episodes; the companion voice is generated by Viterbi in phrase_writer.
"""
import logging
import random
from fractions import Fraction

from builder.types import Note as BuilderNote
from motifs.fragen import Kernel, Note, extract_kernels, sequence_kernels
from motifs.head_generator import degrees_to_midi
from motifs.subject_loader import SubjectTriple
from shared.key import Key
from shared.music_math import parse_metre
from shared.voice_types import Range

_log: logging.Logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_KERNELS_PER_FAMILY: int = 3
_MAX_CANDIDATES: int = 200
_MAX_KERNEL_DURATION: Fraction = Fraction(1, 2)
_MAX_NODES: int = 50000
_MAX_JUNCTION_DEGREES: int = 5  # max diatonic interval at segment boundaries
_MAX_SEGMENTS: int = 5
_SEED: int = 42
_DEGREE_SEARCH_LO: int = -14
_DEGREE_SEARCH_HI: int = 22
_DISTANCE_CANDIDATES: dict[int, tuple[int, ...]] = {
    1: (3, 2, 4, 1),
    2: (5, 4, 6, 3, 7),
    3: (7, 6, 5, 4),
}
_DISTANCE_DEFAULT: tuple[int, ...] = (5, 4, 6, 3, 7, 2)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _closure_ok(segments: list[tuple[Kernel, int]]) -> bool:
    """Last 2 note durations must be >= the preceding 2."""
    durations: list[Fraction] = []
    for k, reps in segments:
        for _ in range(reps):
            durations.extend(k.durations)
    if len(durations) < 4:
        return True
    return (
        durations[-2] >= durations[-4]
        and durations[-1] >= durations[-3]
    )


def _junctions_ok(segments: list[tuple[Kernel, int]], step: int) -> bool:
    """All inter-iteration junctions within _MAX_JUNCTION_DEGREES."""
    for i, (k, reps) in enumerate(segments):
        has_successor: bool = i < len(segments) - 1 or reps > 1
        if has_successor:
            junction: int = step - k.degrees[-1]
            if abs(junction) > _MAX_JUNCTION_DEGREES:
                return False
    return True


def _build_pool(kernels: list[Kernel]) -> list[Kernel]:
    """Keep up to _KERNELS_PER_FAMILY distinct kernels per source family."""
    families: dict[str, list[Kernel]] = {}
    for k in kernels:
        if k.total_duration > _MAX_KERNEL_DURATION:
            continue
        fam: str = k.source.removesuffix("_inv")
        families.setdefault(fam, []).append(k)
    pool: list[Kernel] = []
    for fam in sorted(families.keys()):
        candidates: list[Kernel] = families[fam]
        candidates.sort(key=lambda k: (len(k.degrees), k.total_duration))
        seen_lengths: set[int] = set()
        selected: list[Kernel] = []
        for c in candidates:
            n: int = len(c.degrees)
            if n not in seen_lengths:
                selected.append(c)
                seen_lengths.add(n)
            if len(selected) >= _KERNELS_PER_FAMILY:
                break
        if len(selected) < _KERNELS_PER_FAMILY:
            for c in candidates:
                if c not in selected:
                    selected.append(c)
                if len(selected) >= _KERNELS_PER_FAMILY:
                    break
        pool.extend(selected)
    return pool


def _midi_to_nearest_degree(
    midi: int,
    tonic_midi: int,
    mode: str,
) -> int:
    """Find the scale degree whose MIDI pitch is closest to target."""
    best_deg: int = 1
    best_dist: int = 999
    for deg in range(_DEGREE_SEARCH_LO, _DEGREE_SEARCH_HI):
        m: int = degrees_to_midi((deg,), tonic_midi, mode)[0]
        dist: int = abs(m - midi)
        if dist < best_dist:
            best_dist = dist
            best_deg = deg
    return best_deg


# ---------------------------------------------------------------------------
# EpisodeKernelSource
# ---------------------------------------------------------------------------


class EpisodeKernelSource:
    """Generates unique episode sequences from subject material."""

    def __init__(
        self,
        triple: SubjectTriple,
        seed: int = _SEED,
    ):
        metre_str: str = f"{triple.metre[0]}/{triple.metre[1]}"
        self._bar_length: Fraction = parse_metre(metre=metre_str)[0]
        self._tonic_midi: int = triple.tonic_midi
        self._mode: str = triple.subject.mode
        all_kernels: list[Kernel] = extract_kernels(fugue=triple)
        self._pool: list[Kernel] = _build_pool(kernels=all_kernels)
        self._atoms: list[tuple[int, int, Fraction]] = sorted(
            [
                (idx, reps, k.total_duration * reps)
                for idx, k in enumerate(self._pool)
                for reps in (1, 2)
            ],
            key=lambda a: a[2],
            reverse=True,
        )
        self._used: set[tuple[tuple[str, int], ...]] = set()
        self._rng: random.Random = random.Random(seed)

    @property
    def bar_length(self) -> Fraction:
        """Duration of one bar."""
        return self._bar_length

    @property
    def mode(self) -> str:
        """Scale mode."""
        return self._mode

    @property
    def pool(self) -> list[Kernel]:
        """Kernel pool available for episode construction."""
        return list(self._pool)

    @property
    def pool_size(self) -> int:
        """Number of kernels in the pool."""
        return len(self._pool)

    @property
    def tonic_midi(self) -> int:
        """MIDI pitch of the tonic."""
        return self._tonic_midi

    def generate(
        self,
        start_degree: int,
        finish_degree: int,
        bar_count: int,
    ) -> list[Note] | None:
        """Return degree-space notes for a sequential episode."""
        assert start_degree != finish_degree, (
            f"start {start_degree} must differ from finish {finish_degree}"
        )
        assert bar_count >= 1, f"bar_count must be >= 1, got {bar_count}"
        distance: int = abs(start_degree - finish_degree)
        step: int = -1 if start_degree > finish_degree else 1
        target_dur: Fraction = self._bar_length * bar_count
        segments: list[tuple[Kernel, int]] | None = self._solve(
            target_dur=target_dur,
            distance=distance,
            step=step,
        )
        if segments is None:
            return None
        return sequence_kernels(
            segments=tuple(segments),
            start_degree=start_degree,
            step=step,
        )

    def generate_leader(
        self,
        bar_count: int,
        episode_key: Key,
        leader_track: int,
        leader_range: Range,
        start_offset: Fraction,
        prior_midi: int | None = None,
    ) -> tuple[BuilderNote, ...] | None:
        """Generate leader voice as pipeline-ready builder Notes.

        Picks start/finish degrees from context, converts to MIDI,
        octave-shifts into range. Returns None if no solution found.
        """
        if self.pool_size < 2:
            return None
        tonic_midi: int = episode_key.tonic_pc + 60
        mode: str = episode_key.mode
        # Determine start degree from prior pitch or range centre
        if prior_midi is not None:
            start_deg: int = _midi_to_nearest_degree(
                midi=prior_midi,
                tonic_midi=tonic_midi,
                mode=mode,
            )
        else:
            range_mid: int = (leader_range.low + leader_range.high) // 2
            start_deg = _midi_to_nearest_degree(
                midi=range_mid,
                tonic_midi=tonic_midi,
                mode=mode,
            )
        # Try distance candidates in both directions until one fits
        distances: tuple[int, ...] = _DISTANCE_CANDIDATES.get(
            bar_count, _DISTANCE_DEFAULT,
        )
        for distance in distances:
            for step in (-1, 1):
                finish_deg: int = start_deg + (distance * step)
                notes: list[Note] | None = self.generate(
                    start_degree=start_deg,
                    finish_degree=finish_deg,
                    bar_count=bar_count,
                )
                if notes is None:
                    continue
                result: tuple[BuilderNote, ...] | None = _to_builder_notes(
                    notes=notes,
                    tonic_midi=tonic_midi,
                    mode=mode,
                    track=leader_track,
                    start_offset=start_offset,
                    target_range=leader_range,
                )
                if result is not None:
                    return result
        return None

    def _find_prefixes(
        self,
        remaining_dur: Fraction,
        remaining_iters: int,
        forbidden_last: int,
        path: list[tuple[int, int]],
        results: list[list[tuple[int, int]]],
        budget: list[int],
    ) -> None:
        """DFS for prefix segments summing to exact (dur, iters)."""
        budget[0] -= 1
        if budget[0] <= 0:
            return
        if remaining_dur == Fraction(0) and remaining_iters == 0:
            if not path or path[-1][0] != forbidden_last:
                results.append(list(path))
            return
        if remaining_iters <= 0 or remaining_dur <= Fraction(0):
            return
        if len(path) >= _MAX_SEGMENTS - 1:
            return
        if len(results) >= _MAX_CANDIDATES:
            return
        for idx, reps, dur in self._atoms:
            if dur > remaining_dur:
                continue
            if reps > remaining_iters:
                continue
            if path and path[-1][0] == idx:
                continue
            path.append((idx, reps))
            self._find_prefixes(
                remaining_dur=remaining_dur - dur,
                remaining_iters=remaining_iters - reps,
                forbidden_last=forbidden_last,
                path=path,
                results=results,
                budget=budget,
            )
            path.pop()
            if len(results) >= _MAX_CANDIDATES or budget[0] <= 0:
                return

    def _solve(
        self,
        target_dur: Fraction,
        distance: int,
        step: int,
    ) -> list[tuple[Kernel, int]] | None:
        """Find a unique segment list filling target_dur with given distance."""
        candidates: list[list[tuple[Kernel, int]]] = []
        for last_idx in range(len(self._pool)):
            last_k: Kernel = self._pool[last_idx]
            last_deg: int = last_k.degrees[-1]
            for last_reps in (1, 2):
                last_dur: Fraction = last_k.total_duration * last_reps
                if last_dur > target_dur:
                    continue
                if step == -1:
                    total_iters: int = distance + last_deg + 1
                else:
                    total_iters = distance - last_deg + 1
                if total_iters < last_reps or total_iters < 1:
                    continue
                prefix_iters: int = total_iters - last_reps
                prefix_dur: Fraction = target_dur - last_dur
                suffix: list[tuple[Kernel, int]] = [(last_k, last_reps)]
                if prefix_iters == 0 and prefix_dur == Fraction(0):
                    candidates.append(suffix)
                    if len(candidates) >= _MAX_CANDIDATES:
                        break
                    continue
                if prefix_iters <= 0 or prefix_dur <= Fraction(0):
                    continue
                prefixes: list[list[tuple[int, int]]] = []
                self._find_prefixes(
                    remaining_dur=prefix_dur,
                    remaining_iters=prefix_iters,
                    forbidden_last=last_idx,
                    path=[],
                    results=prefixes,
                    budget=[_MAX_NODES],
                )
                for p in prefixes:
                    segments: list[tuple[Kernel, int]] = [
                        (self._pool[idx], reps) for idx, reps in p
                    ] + suffix
                    candidates.append(segments)
                    if len(candidates) >= _MAX_CANDIDATES:
                        break
                if len(candidates) >= _MAX_CANDIDATES:
                    break
            if len(candidates) >= _MAX_CANDIDATES:
                break
        self._rng.shuffle(candidates)
        # Pick first with novel family key, valid closure, and smooth junctions
        for c in candidates:
            if not _closure_ok(segments=c):
                continue
            if not _junctions_ok(segments=c, step=step):
                continue
            key: tuple[tuple[str, int], ...] = tuple(
                (k.source.removesuffix("_inv"), r) for k, r in c
            )
            if key not in self._used:
                self._used.add(key)
                return c
        # Exhaustion: reset used set and retry with fresh tracking
        self._used.clear()
        for c in candidates:
            if not _closure_ok(segments=c):
                continue
            if not _junctions_ok(segments=c, step=step):
                continue
            key = tuple(
                (k.source.removesuffix("_inv"), r) for k, r in c
            )
            if key not in self._used:
                self._used.add(key)
                return c
        return None


# ---------------------------------------------------------------------------
# Pipeline adapter
# ---------------------------------------------------------------------------


def _to_builder_notes(
    notes: list[Note],
    tonic_midi: int,
    mode: str,
    track: int,
    start_offset: Fraction,
    target_range: Range,
) -> tuple[BuilderNote, ...] | None:
    """Convert degree-space notes to builder Notes, octave-shifted into range."""
    midi_pitches: list[int] = [
        degrees_to_midi((n.degree,), tonic_midi, mode)[0]
        for n in notes
    ]
    if not midi_pitches:
        return None
    # Octave-shift into target range.
    # The valid shift window is [range.low - lowest, range.high - highest].
    # Find the multiple of 12 nearest the centre of that window.
    lowest: int = min(midi_pitches)
    highest: int = max(midi_pitches)
    span: int = highest - lowest
    range_span: int = target_range.high - target_range.low
    if span > range_span:
        _log.warning(
            "Episode kernel span %d st exceeds range span %d st "
            "[%d, %d]; cannot fit",
            span, range_span, target_range.low, target_range.high,
        )
        return None
    shift_lo: int = target_range.low - lowest
    shift_hi: int = target_range.high - highest
    # Find best multiple of 12 in [shift_lo, shift_hi]
    first_candidate: int = ((shift_lo + 11) // 12) * 12  # ceil to next mult of 12
    if shift_lo <= 0 <= shift_hi:
        first_candidate = 0  # prefer no shift
    else:
        first_candidate = ((shift_lo + 11) // 12) * 12 if shift_lo > 0 else (shift_lo // 12) * 12
    shift: int | None = None
    for candidate in range(first_candidate, shift_hi + 1, 12):
        if shift_lo <= candidate <= shift_hi:
            shift = candidate
            break
    if shift is None:
        # No exact octave shift works — try centring within range
        centre_shift: int = (shift_lo + shift_hi) // 2
        nearest_octave: int = round(centre_shift / 12) * 12
        if shift_lo <= nearest_octave <= shift_hi:
            shift = nearest_octave
    if shift is None:
        _log.warning(
            "Episode kernel cannot fit in range [%d, %d]: "
            "span %d-%d, valid shift window [%d, %d] has no multiple of 12",
            target_range.low, target_range.high, lowest, highest, shift_lo, shift_hi,
        )
        return None
    result: list[BuilderNote] = []
    for note, midi in zip(notes, midi_pitches):
        result.append(BuilderNote(
            offset=note.offset + start_offset,
            pitch=midi + shift,
            duration=note.duration,
            voice=track,
            creator="episode_kernel",
        ))
    return tuple(result)
